language: android
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used
    - build-tools-19.1.0
  
    # The SDK version used to compile
    - android-19
  
    # Additional components
    - extra
    # - extra-android-support
    # - extra-google-google_play_services

jdk:
  - oraclejdk8
  - oraclejdk7