sudo: true

language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo yes | sdkmanager "platforms;$ANDROID_TARGET" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

script:
  - ./gradlew check
