language: android
android:
  components:
    # The BuildTools version used
    - build-tools-21
  
    # The SDK version used to compile
    - android-21
  
    # Additional components
    - extra-android-support