language: android
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used
    - build-tools-19.1.0
  
    # The SDK version used to compile
    - android-19
  
    # Additional components
    - extra
    # - extra-android-support
    # - extra-google-google_play_services

jdk:
  - oraclejdk7
  # Disable JDK8 for the time being, due to failed task ':app:preDexDebug'
  # Cause: project and library are compiled by different versions of JDK
  # - oraclejdk8

before_install:
  - echo yes | android update sdk --all --filter build-tools-21.1.2 --no-ui --force > /dev/null

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &